function [net,traininfo] = LSTM_model(CP1noDis,CP2noDis,nh)
[dsTrain,dsTest] = preprocess(CP1noDis)
[valTrain,valTest] = preprocess(CP2noDis)
opts = trainingOptions("adam",...
    "ExecutionEnvironment","auto",...
    "InitialLearnRate",0.035,...
    "L2Regularization",0.0012,...
    "LearnRateSchedule","piecewise",...
    "Shuffle","every-epoch",...
    "Plots","training-progress",...
    "ValidationData",valTrain);
layers = [
    sequenceInputLayer(1,"Name","sequence")
    lstmLayer(nh,"Name","lstm")
    fullyConnectedLayer(1,"Name","fc")
    dropoutLayer(0.075,"Name","dropout")
    regressionLayer("Name","regressionoutput")];
[net, traininfo] = trainNetwork(dsTrain,layers,opts);
end
